### ISSUE TITLE
Add unreachable() to SwapSlot::load() for None option 

### ISSUE THREAD

**Issue by filipdulic** [filipdulic/bus-queue#53]
fix up SwapSlot::load() implementations for all flavors to cover None option, use it in flavor tests by expecting panic. 
```
let result = std::panic::catch_unwind(|| SwapSlot::load(&item));
assert!(result.is_err());
```

**Comment by stevanmilic** [comment]
I'm not sure I understand the issue. The functions already panics when it encounters `None` since it `unwrap`s the value from a slot implementation.
Did you mean that the `None` case should be handled and `Option<Arc<T>` should be returned? That has a lot of more sense,  IMO. You did mention that it would never happen tho.

**Comment by filipdulic** [comment]
It's a compiler optimization thing. You tell the compiler that that arm of code is unreachable, and it will optimize it's compilation around that option. It will panic in both cases, only in this case the code is more verbose about what happens, and the binary is better optimized around it.

**Comment by filipdulic** [comment]
But, I agree returning Option<Arc<T>> is a better option. no pun intended.
